import{DatabaseSync}from'node:sqlite';import{readFile,readdir}from'node:fs/promises';import assert from'node:assert/strict';import worker from'../dist/server/index.js';
const d=new DatabaseSync(':memory:');d.exec('PRAGMA foreign_keys=ON');for(const f of(await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())d.exec(await readFile('drizzle/'+f,'utf8'));
class Q{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Q(this.sql,args)}async first(){return d.prepare(this.sql).get(...this.args)||null}async all(){return{results:d.prepare(this.sql).all(...this.args)}}async run(){return{meta:{changes:Number(d.prepare(this.sql).run(...this.args).changes)}}}}
const env={DB:{prepare:s=>new Q(s),async batch(items){d.exec('BEGIN');try{const out=[];for(const q of items)out.push(await q.run());d.exec('COMMIT');return out}catch(e){d.exec('ROLLBACK');throw e}}}};
const owner={};let cookie='';async function call(path,body,headers={},student=false){const r=await worker.fetch(new Request('https://practice.test'+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json',Origin:'https://practice.test'}),...(student?{Cookie:cookie}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}),env);const t=await r.text();let data;try{data=JSON.parse(t)}catch{data=t}return{status:r.status,data,headers:r.headers}}
assert.equal((await call('/api/bank')).status,401);assert.equal((await call('/api/admin/overview')).status,403);assert.equal((await call('/bank.json')).status,403);
env.INSTRUCTOR_USERNAME='claire';env.INSTRUCTOR_PASSWORD_SALT='test-only-salt';
const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('Instructor test password!'),'PBKDF2',false,['deriveBits']);env.INSTRUCTOR_PASSWORD_HASH=Buffer.from(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(env.INSTRUCTOR_PASSWORD_SALT),iterations:100000,hash:'SHA-256'},key,256)).toString('hex');
assert.equal((await call('/api/admin/overview',undefined,{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'clairewjs@gmail.com'})).status,403);
assert.equal((await call('/api/instructor/login',{username:'claire',password:'wrong'})).status,401);
const adminLogin=await call('/api/instructor/login',{username:'claire',password:'Instructor test password!'});assert.equal(adminLogin.status,200);owner.Cookie=adminLogin.headers.get('set-cookie').split(';')[0];
const created=await call('/api/admin/students',{students:[{name:'Test student',username:'test-001'},{name:'=CSV safety',username:'test-002'}]},owner);assert.equal(created.status,201);const creds=created.data.credentials;
assert.equal((await call('/api/login',{username:creds[0].username,password:'incorrect'})).status,401);
let login=await call('/api/login',{username:creds[0].username,password:creds[0].password});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly/);assert.match(login.headers.get('set-cookie'),/Secure/);cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await call('/api/bank',undefined,{},true)).status,403);assert.equal((await call('/api/password',{password:'short'},{},true)).status,400);assert.equal((await call('/api/password',{password:'Student passphrase 2026!'},{},true)).status,200);
const bank=(await call('/api/bank',undefined,{},true)).data;assert.equal(bank.sets.length,10);assert.equal(bank.sets[0].questions[0].answer,undefined);assert.equal(bank.sets[0].questions[0].rationale,undefined);assert.equal((await call('/api/admin/overview',undefined,{},true)).status,403);
let a=(await call('/api/attempts',{set:0,mock:false},{},true)).data.attempt;assert.equal(a.questions.length,6);assert.equal(a.questions[0].answer,undefined);assert.equal((await call('/api/attempts',{set:1},{},true)).data.attempt.id,a.id);
const original=JSON.parse(await readFile('public/bank.json','utf8')),answer=original.sets[0].questions[0].answer;let submitted=await call(`/api/attempts/${a.id}/answer`,{index:0,answer,correct:6,percent:100},{},true);assert.equal(submitted.status,200);assert.equal(submitted.data.attempt.index,1);assert.equal((await call(`/api/attempts/${a.id}/answer`,{index:0,answer},{},true)).status,200);assert.equal((await call(`/api/attempts/${a.id}/answer`,{index:0,answer:[(answer[0]+1)%4]},{},true)).status,409);assert.equal((await call(`/api/attempts/${a.id}/answer`,{index:2,answer:[0]},{},true)).status,409);
for(let i=1;i<6;i++){submitted=await call(`/api/attempts/${a.id}/answer`,{index:i,answer:original.sets[0].questions[i].answer},{},true);assert.equal(submitted.status,200)}assert.equal(submitted.data.attempt.correct,6);assert.equal(submitted.data.attempt.percent,100);assert.equal(submitted.data.attempt.status,'completed');assert.ok(submitted.data.attempt.questions[0].rationale);assert.equal((await call('/api/tip',{lesson:0,answer:0},{},true)).data.correct,true);
const overview=(await call('/api/admin/overview',undefined,owner)).data;assert.equal(overview.students.find(s=>s.username==='test-001').sets_done,1);assert.ok(overview.activity.some(l=>l.event==='completed'));const exported=await call('/api/admin/export?type=students',undefined,owner);assert.match(exported.data,/'=CSV safety/);assert.equal((await call('/api/admin/attempts/'+a.id,undefined,owner)).data.attempt.correct,6);
login=await call('/api/login',{username:creds[1].username,password:creds[1].password});cookie=login.headers.get('set-cookie').split(';')[0];await call('/api/password',{password:'Different passphrase 2026'},{},true);assert.equal((await call(`/api/attempts/${a.id}/answer`,{index:0,answer:[0]},{},true)).status,404);a=(await call('/api/attempts',{mock:true},{},true)).data.attempt;d.prepare('UPDATE attempts SET deadline=? WHERE id=?').run(Date.now()-1,a.id);const timeout=(await call(`/api/attempts/${a.id}/status`,undefined,{},true)).data.attempt;assert.equal(timeout.status,'timed_out');assert.equal(timeout.correct,0);assert.equal(timeout.total,60);
assert.equal((await call('/api/admin/students/'+creds[1].id+'/access',{active:false},owner)).status,200);assert.equal((await call('/api/me',undefined,{},true)).data.user,null);const reset=await call('/api/admin/students/'+creds[0].id+'/reset',{},owner);assert.equal(reset.status,200);assert.notEqual(reset.data.credentials[0].password,creds[0].password);assert.equal(d.prepare('SELECT COUNT(*) AS n FROM attempts').get().n,2);assert.equal((await call('/api/login',{username:'test-001',password:'wrong'},{Origin:'https://other.test'})).status,403);
console.log('PASS: migrations, credentials, password change, protected keys, role separation, server scoring, locked answers, resume, cross-student isolation, timeout, central activity, CSV safety, reset, disable, CSRF.');
// Render checks using the real API and a minimal DOM surface; no browser preview is available for this Worker.
const {default:vm}=await import('node:vm');const elements=new Map();function element(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',querySelectorAll:()=>[],querySelector:()=>null,scrollIntoView(){}});return elements.get(id)}
const context={document:{getElementById:element,createElement:()=>({click(){}})},window:{scrollTo(){}},location:{origin:'https://practice.test',href:'https://practice.test/'},fetch:async(path,options={})=>worker.fetch(new Request('https://practice.test'+path,{...options,headers:{...owner,...options.headers}}),env),console,Date,Math,JSON,Set,Blob,URL,FormData,setTimeout,clearInterval,setInterval,alert(){},confirm:()=>true};vm.createContext(context);vm.runInContext(await readFile('public/app.js','utf8'),context);await new Promise(resolve=>setTimeout(resolve,30));assert.match(element('app').innerHTML,/Student access & activity/);
vm.runInContext(`for(const v of ['home','learn','practice','mock','results','resources']){view=v;reviewResult=null;render()}renderLogin();renderPassword();`,context);assert.match(element('app').innerHTML,/Choose your own password/);context.testResult=submitted.data.attempt;vm.runInContext('renderResult(testResult)',context);assert.match(element('app').innerHTML,/100%/);console.log('PASS: instructor dashboard, six learning views, login, password setup, result review render.');
